### ISSUE TITLE
Build fails with Android Studio 3 (Update protobuf plugin to 0.8.2)

### ISSUE THREAD

**Issue by proppy** [androidthings/sample-googleassistant#23]
```Could not determine the dependencies of task ':app:extractIncludeDebugProto'.
> Resolving configuration 'debugCompile' directly is not allowed

remove 'jackOptions { ... }' from your build.gradle file, and add

android.compileOptions.sourceCompatibility 1.8
android.compileOptions.targetCompatibility 1.8
```

**Comment by mhanuel26** [comment]
Just want to know about the status of this, I handle to compile using 3.0 by changing

classpath "com.google.protobuf:protobuf-gradle-plugin:0.8.0"

with 

classpath "com.google.protobuf:protobuf-gradle-plugin:0.8.2"

it's documented here

https://github.com/google/protobuf-gradle-plugin/issues/129

it compiles but still with the jackOptions warnings.

I am just trying to make it work since the app runs and I can see someactivity on the console and even I can see the traffic in google services dashboard but the device don't output sound at all.

Here is the console output

_09-20 14:45:38.290 1421-1421/? I/zygote: Late-enabling -Xcheck:jni
09-20 14:45:38.455 1421-1421/? W/zygote: Using default instruction set features for ARM CPU variant (generic) using conservative defaults
09-20 14:45:39.626 1421-1421/com.example.androidthings.assistant I/InstantRun: starting instant run server: is main process
09-20 14:45:39.896 1421-1421/com.example.androidthings.assistant I/AssistantActivity: starting assistant demo
09-20 14:45:40.285 1421-1421/com.example.androidthings.assistant I/AssistantActivity: creating voice hat driver
09-20 14:45:40.458 1421-1421/com.example.androidthings.assistant I/AssistantActivity: setting volume to: 15
09-20 14:45:40.480 1421-1421/com.example.androidthings.assistant D/AudioTrack: Client defaulted notificationFrames to 1202 for frameCount 2404
09-20 14:45:40.633 1421-1421/com.example.androidthings.assistant D/NetworkSecurityConfig: No Network Security Config specified, using platform default
09-20 14:45:41.336 1421-1421/com.example.androidthings.assistant I/vndksupport: sphal namespace is not configured for this process. Loading /vendor/lib/hw/gralloc.gbm.so from the current namespace instead.
09-20 14:45:50.999 1421-1453/com.example.androidthings.assistant I/AssistantActivity: starting assistant request
09-20 14:45:51.137 1421-1453/com.example.androidthings.assistant D/AssistantActivity: streaming ConverseRequest: 1024
09-20 14:45:51.781 1421-1453/com.example.androidthings.assistant I/chatty: uid=10029(u0_a29) assistantThread identical 22 lines
09-20 14:45:51.841 1421-1453/com.example.androidthings.assistant D/AssistantActivity: streaming ConverseRequest: 1024
09-20 14:45:51.843 1421-1453/com.example.androidthings.assistant I/AssistantActivity: ending assistant request
09-20 14:45:54.251 1421-1453/com.example.androidthings.assistant I/AssistantActivity: ending assistant request
09-20 14:45:54.415 1421-1475/com.example.androidthings.assistant I/AssistantActivity: assistant response finished
09-20 14:46:04.098 1421-1453/com.example.androidthings.assistant I/AssistantActivity: starting assistant request
09-20 14:46:04.233 1421-1453/com.example.androidthings.assistant D/AssistantActivity: streaming ConverseRequest: 1024
09-20 14:46:05.072 1421-1453/com.example.androidthings.assistant I/chatty: uid=10029(u0_a29) assistantThread identical 27 lines
09-20 14:46:05.129 1421-1453/com.example.androidthings.assistant D/AssistantActivity: streaming ConverseRequest: 1024
09-20 14:46:05.132 1421-1453/com.example.androidthings.assistant I/AssistantActivity: ending assistant request
09-20 14:46:05.345 1421-1475/com.example.androidthings.assistant I/AssistantActivity: assistant response finished
09-20 14:46:15.185 1421-1453/com.example.androidthings.assistant I/AssistantActivity: starting assistant request
09-20 14:46:15.321 1421-1453/com.example.androidthings.assistant D/AssistantActivity: streaming ConverseRequest: 1024
09-20 14:46:15.772 1421-1453/com.example.androidthings.assistant I/chatty: uid=10029(u0_a29) assistantThread identical 15 lines
09-20 14:46:15.833 1421-1453/com.example.androidthings.assistant D/AssistantActivity: streaming ConverseRequest: 1024
09-20 14:46:15.837 1421-1453/com.example.androidthings.assistant I/AssistantActivity: ending assistant request
09-20 14:46:16.106 1421-1475/com.example.androidthings.assistant I/AssistantActivity: assistant response finished
09-20 14:46:42.406 1421-1453/com.example.androidthings.assistant I/AssistantActivity: ending assistant request_

**Comment by Fleker** [comment]
Odd. I've been running the project in AS3 without any issue. I'll update the issue to note updating dependency.

Re sound: It may be more useful to look at your AudioTrack parameters and try to play general sound instead of adding in the Assistant first.

**Comment by mhanuel26** [comment]
Hi Fleker, I make it work, I think it was something to do with initial permissions. 

I just notice the audio output is clipped of has serious cuts when giving answers, do you think it might be related to AndroidThings project ? Or debugging ? Bot sure how can I test the app without having to do Run in Android Studio.

Also I am seeing this at console output every while. But 

`E/AssistantActivity: converse error:
                                                                                      io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on DATA frame from server.
                                                                                          at io.grpc.Status.asRuntimeException(Status.java:540)
                                                                                          at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:392)
                                                                                          at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:428)
                                                                                          at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
                                                                                          at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:514)
                                                                                          at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:431)
                                                                                          at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:546)
                                                                                          at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
                                                                                          at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                          at java.lang.Thread.run(Thread.java:764)`

**Comment by Fleker** [comment]
Are you doing anything when the Assistant responds, like toggling the LED?

If the app still works without Jack I guess it's fine. It is a compiler extension which supports Java 8 language features. If we haven't used Java 8 in the project it won't make a difference.

**Comment by mhanuel26** [comment]
Actually I haven't modify at all the code.

Seems like a buffer problem since it starts the first three or four words of answer without clipping but then starts to cut seriously, it's noticed more if answer takes longer time. 

Not sure how to debug the thing, anything you might think I can try just let me know please.

**Comment by Fleker** [comment]
I don't think that underrun message is normal. Let's make a new issue for this.

**Comment by mhanuel26** [comment]
Hi @Fleker , Just don't know where to start, I would like to provide more debugging information, if you can suggest me something I can try as well,
Please let me know,
