### ISSUE TITLE
How to find the end of audio response ?

### ISSUE THREAD

**Issue by Ranjith1992** [androidthings/sample-googleassistant#36]
I want to know the end of audio response(audio out) to start a new session.
Use case:
User : Set alarm
Response : what time ?

User : 6:30
Response : Ok,Setting alarm to 6:30

For this case, i need to know audio finish status after the response "what time ?" to start new session.

Kindly help .

**Comment by Fleker** [comment]
You can listen to the Converse Response event END OF UTTERANCE.

**Comment by proppy** [comment]
Maybe we could update the sample to listen for `END_OF_UTTERANCE`?

**Comment by Fleker** [comment]
Yeah definitely working on it

On Aug 9, 2017 5:08 AM, "Johan Euphrosine" <notifications@github.com> wrote:

Maybe we could update the sample to listen for END_OF_UTTERANCE?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/androidthings/sample-googleassistant/issues/36#issuecomment-321236569>,
or mute the thread
