### ISSUE TITLE
Log in issue  in android smart phone

### ISSUE THREAD

**Issue by Ranjith1992** [androidthings/sample-googleassistant#38]
I  created a sample google assinstant app for android smart phone by referring this code.
But if i want to login from another Google account i need to change the credential.json  file.
How i can overcome this?
There anyway to prompt Google account login for grpc authentication?

**Comment by Fleker** [comment]
At the moment there's not a good way to change the credentials without
sharing the project with another person.

On Aug 22, 2017 10:53 PM, "Ranjith1992" <notifications@github.com> wrote:

I created a sample google assinstant app for android smart phone by
referring this code.
But if i want to login from another Google account i need to change the
credential.json file.
How i can overcome this?
There anyway to prompt Google account login for grpc authentication?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/androidthings/sample-googleassistant/issues/38>, or mute
the thread

**Comment by Ranjith1992** [comment]
I can see many other methods like withChannel,withCompression,withDeadlinewithInterceptors..etc
How to use these instead of withCallCredentials.

**Comment by CCCCoder** [comment]
@Ranjith1992 Hi , Could you tell me how to integrate this on Android phone?

**Comment by Ranjith1992** [comment]
@CCCCoder Hi,I refereed this application code and created an application for phone.

**Comment by tanishkgupta** [comment]
Hi @Ranjith1992 , Please help us by sharing details on how to integrate this on Android phone as well!
